### PR TITLE
Bugfix/fix wildcard queries

### PR DESCRIPTION
**Pull request by ifesdjeen**
Make sure that combined traversals work, split traversals for single and multi-series

    Queries need to work for several cases:

    1. When we combine series, sum
    2. When we map series, absolute
    3. When we reduce series, derivative
    4. Combination of any

    Since (1) is different from all the others, in the way it combines
    series and has to do (apply mapv ...), we have to make a separate
    function for it. FWIW, reducer and mapper _might_ be safely removed
    from there.

    To handle (2) and (3) in simpler way, `traverse-each!` was added,
    that handles operations on singlular series.

### CODE REVIEW

**Comment by ifesdjeen** [comment]
I hope that one already works sufficiently well for all the cases, many tests, including integration ones are added. Contracts are established.

**Comment by ifesdjeen** [comment]
Hey @pyr could you take a look so I could continue further development? :)

**Comment by zbintliff** [comment]
Just letting you know, we are currently building from `master` but the graphite-api can not query past the first metric (i.e. can query `*` but not `foo.*`).  That is what I'm guessing this PR is supposed to fix.

So I built the jar using this branch and it failed to even validate a single query using graphite-api.  Meaning I couldn't even verify the source in grafana because a simple search (`curl 'localhost:8000/metrics/find?query=*'` fails on this branch.

**Comment by zbintliff** [comment]
You can use my docker-compose file located [here](https://github.com/zbintliff/cyanite-docker) to recreate.  The current jar being used is from master. But if you build from the one in this branch, place it there do a `docker-compose build --no-cache && docker-compose up -d` it should replace the cyanite instance with the new one.

**Comment by ifesdjeen** [comment]
Thanks for the hint @zbintliff I'll look right into it tonight!

**Comment by zbintliff** [comment]
No problem.  The current setup of the compose is grafana -> graphite-api (cyanite plugin) -> cyanite service.  

Not sure if the change in this PR is supposed to require a change to the cyanite api plugin.

**Comment by ifesdjeen** [comment]
TBH I'd recommend using grafana directly without cyanite plugin. At least I don't see any advantage in using graphite-api there. Or if you can explain, I could learn something new :)

**Comment by zbintliff** [comment]
Didn't know that was possible! We are following the old documentation on cyanite.io. 

Are you saying no intermediary api is needed for grafana to communicate with cyanite?

**Comment by ifesdjeen** [comment]
Yes, there's no api needed to communicate between grafana/cyanite as long as you're using grafana in "proxy" mode (which is a matter of picking the right item from the dropbox)...

**Comment by zbintliff** [comment]
Thanks for the tip! I am still unable to connect grafana to the cyanite http service 8080 the JAR built from this branch though (master can validate at least though!)

**Comment by chaosong** [comment]
It seems that cyanite http service doesn't support as much functions as graphite-api does

**Comment by ifesdjeen** [comment]
Could you be a bit more elaborate @chaosong? As it might be that cyanite doesn't support them either :)

**Comment by ifesdjeen** [comment]
@zbintliff I've tried your query on the latest branch, it returns results just fine...

```
http://localhost:8080/metrics/find?query=*
[{"text":"STRESS","id":"STRESS","allowChildren":true,"expandable":true,"leaf":false},{"text":"internal","id":"internal","allowChildren":true,"expandable":true,"leaf":false}]
```

Could you please post the stacktrace here? Also, I'd advise to rebuild the jar (`lein clean && lein uberjar`) just in case. 

I'm currently testing with `make dev` most of the time, since this is less prone to cached classfiles and stuff.

**Comment by zbintliff** [comment]
From branch master:
```
$ md5 target/cyanite-0.5.1-standalone.jar
MD5 (target/cyanite-0.5.1-standalone.jar) = 8c938249daad838ebdde916d592c416f
$ curl http://localhost:8080/metrics/find?query=*
[{"text":"docker","id":"docker","path":"docker","allowChildren":true,"expandable":true,"leaf":false}]
$ curl http://localhost:8080/metrics/find?query=docker.*
{"message":"Query execution failed"}
```
Stack Trace is quite large, [here is the gist](https://gist.github.com/zbintliff/dc223462ab3e1502705fd8cbbf10ec21)

Build off of branch `bugfix/fix-wildcard-queries`:
```
$ md5 target/cyanite-0.5.1-standalone.jar
MD5 (target/cyanite-0.5.1-standalone.jar) = 7ea605dc4e6ba58dd30260e1164f3b14
$ curl http://localhost:8080/metrics/find?query=*
[{"text":"docker","id":"docker","allowChildren":true,"expandable":true,"leaf":false}]np
$ curl http://localhost:8080/metrics/find?query=docker.*
{"message":"Query execution failed"}
```
[Stack trace](https://gist.github.com/zbintliff/b8b700e195633764173f3867d7d30fed) (looks the same)

Grafana can register the one off of master as a data source but not off of this branch.
screen shot 2016-07-18 at 3 52 38 pm

**Comment by ifesdjeen** [comment]
All right. 
Thing is that we use SASI indexes that first shipped with Cassandra 3.4 iirc. So Cyanite can't really work without them. At least that's what I can see from the stack trace (`LIKE` syntax unrecognised). Also, I'd say there's no reason not to be on 3.4 if you're already in 3.x world.

**Comment by zbintliff** [comment]
That was the issue.  I was use 3.0 which introduced the SASI indexes but I guess 3.4 introduced the syntax you were using.  Sorry to drag you through all of this in a PR

**Comment by ifesdjeen** [comment]
Unfortunately no, we don't have IRC or the mailing list so far. But I can set up one. I'm completely fine to handle it here though. 

Ah, that's true, SASI was introduced earlier. Meant `LIKE` syntax, you're completely right there.

**Comment by zbintliff** [comment]
Ok, so now I can query and not get error but it seems like it is only ever returning one result instead of all paths.

To show you what I mean here is a print of my `prefix` table in Cassandra:
```
cqlsh> use metric;
cqlsh:metric> select * from path;

 prefix                             | path                                       | length
------------------------------------+--------------------------------------------+--------
         first.collectd.write_queue |    first.collectd.write_queue.queue_length |      4
        second.collectd.write_queue |   second.collectd.write_queue.queue_length |      4
  first.collectd.write_queue.derive |  first.collectd.write_queue.derive.dropped |      5
                    first.cpu.1.cpu |                       first.cpu.1.cpu.idle |      5
                    first.cpu.1.cpu |                  first.cpu.1.cpu.interrupt |      5
                    first.cpu.1.cpu |                       first.cpu.1.cpu.nice |      5
                    first.cpu.1.cpu |                    first.cpu.1.cpu.softirq |      5
                    first.cpu.1.cpu |                      first.cpu.1.cpu.steal |      5
                    first.cpu.1.cpu |                     first.cpu.1.cpu.system |      5
                    first.cpu.1.cpu |                       first.cpu.1.cpu.user |      5
                    first.cpu.1.cpu |                       first.cpu.1.cpu.wait |      5
                    first.cpu.0.cpu |                       first.cpu.0.cpu.idle |      5
                    first.cpu.0.cpu |                  first.cpu.0.cpu.interrupt |      5
                    first.cpu.0.cpu |                       first.cpu.0.cpu.nice |      5
                    first.cpu.0.cpu |                    first.cpu.0.cpu.softirq |      5
                    first.cpu.0.cpu |                      first.cpu.0.cpu.steal |      5
                    first.cpu.0.cpu |                     first.cpu.0.cpu.system |      5
                    first.cpu.0.cpu |                       first.cpu.0.cpu.user |      5
                    first.cpu.0.cpu |                       first.cpu.0.cpu.wait |      5
              second.collectd.cache |           second.collectd.cache.cache_size |      4
 second.collectd.write_queue.derive | second.collectd.write_queue.derive.dropped |      5
               first.collectd.cache |            first.collectd.cache.cache_size |      4
                   second.cpu.0.cpu |                 second.cpu.0.cpu.interrupt |      5
                   second.cpu.0.cpu |                      second.cpu.0.cpu.nice |      5
                   second.cpu.0.cpu |                   second.cpu.0.cpu.softirq |      5
                   second.cpu.0.cpu |                    second.cpu.0.cpu.system |      5
                   second.cpu.0.cpu |                      second.cpu.0.cpu.user |      5
                   second.cpu.0.cpu |                      second.cpu.0.cpu.wait |      5
                   second.cpu.1.cpu |                      second.cpu.1.cpu.nice |      5
                   second.cpu.1.cpu |                    second.cpu.1.cpu.system |      5
                   second.cpu.1.cpu |                      second.cpu.1.cpu.user |      5
                   second.cpu.1.cpu |                      second.cpu.1.cpu.wait |      5
```
Query just `*`
```
[cyanite/ (master *)]$ curl http://localhost:8080/metrics/find?query=*
[{"text":"first","id":"first","allowChildren":true,"expandable":true,"leaf":false},{"text":"second","id":"second","allowChildren":true,"expandable":true,"leaf":false}]
```
returns both children.

However if I search `first.*` it should return `cpu` and `collectd` but only returns collectd.
```
$ curl http://localhost:8080/metrics/find?query=first.*
[{"text":"collectd","id":"first.collectd","allowChildren":true,"expandable":true,"leaf":false}]
```

**Comment by ifesdjeen** [comment]
🎆 thank you @zbintliff, also thanks a lot for the docs patch and for giving cyanite a shot!

**Comment by zbintliff** [comment]
Still having issues actually querying metric (grafana shows blank and I get null messages). But I want to be absolutely sure its not a user error before posting here again.

**Comment by ifesdjeen** [comment]
Hm. The first and foremost is that we support not that many commands that graphite supports. 

Hit me up on IRC (same nickname as here), feel free to post stacktraces in any quantity there.

**Comment by asafm** [comment]
Do you guys have a list of implemented/non-implemented graphite commands?

**Comment by ifesdjeen** [comment]
@asafm since we didn't yet have a release, no, not really. This branch is "in review" and so far this is the "most complete" implementation, so best list would be here: https://github.com/pyr/cyanite/blob/f503ee11275866f4295267d750bbb7cb48a24571/test/io/cyanite/query/ast_test.clj

So it's just `sum`, `derivative`, `absolute` and `scale`: we picked sample commands of each "type": ones that'd perform aggregations across metrics, within metric (stateful), and stateless. 

Although adding new ones is trivial.

**Comment by ifesdjeen** [comment]
After talking to @leoleovich i've noticed that indexes will have hard times when working with extremely large data sets. While it is impossible to optimise for every use-case, I was able to significantly improve the situation with metrics that:

a) can be retrieved by fetching parent (anything that can be globbed like `a.b.*` 
b) root queries are now super-fast (`*`)
c) `a.*.c` - like queries are the only ones that require filtering, but one has to pay for such queries, so I think it's fair: we allow them, but there's no way we can optimise them further

Schema is updated.

**Comment by tehlers320** [comment]
You did indeed get the queries running super fast for * however queries directly to a metric are still broken

```
time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-*.aggregation-cpu-average.percent-user
[{"text":"percent-user","id":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","path":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","allowChildren":false,"expandable":false,"leaf":true}]
real	0m0.209s
user	0m0.000s
sys	0m0.000s
```

```
time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user
[{"text":"percent-user","id":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","path":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","allowChildren":false,"expandable":false,"leaf":true}]
real	0m13.618s
user	0m0.000s
sys	0m0.000s

```

**Comment by ifesdjeen** [comment]
@tehlers320  Did you migrate the schema?

**Comment by tehlers320** [comment]
@ifesdjeen 


i'm using this one, or was there another update i missed?
https://github.com/pyr/cyanite/blob/bugfix/fix-wildcard-queries/doc/schema.cql

I went ahead and dropped the entire keyspace and re-setup with https://github.com/pyr/cyanite/blob/bugfix/fix-wildcard-queries/doc/schema.cql

The first few queries were very fast but as the segment table populates it takes longer and longer

```
time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-*.aggregation-cpu-average.percent-user
[{"text":"percent-user","id":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","path":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","allowChildren":false,"expandable":false,"leaf":true}]
real	0m0.039s

time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user
[{"text":"percent-user","id":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","path":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","allowChildren":false,"expandable":false,"leaf":true}]
real	0m1.682s

time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user
[{"text":"percent-user","id":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","path":"collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user","allowChildren":false,"expandable":false,"leaf":true}]
real	0m3.975s
```


The cassandra query itself is taking .8 seconds but its sending all 333k metrics 
` e2103343-5f25-11e6-90b7-c39077eaae1b |  10.2.95.6 |   QUERY |  10.2.92.37 |   796915 |                                                                  {'consistency_level': 'LOCAL_ONE', 'page_size': '5000', 'query': 'SELECT * from segment where segment LIKE ''collectd_metrics%'' AND pos = 5', 'serial_consistency_level': 'SERIAL'} |          Execute CQL3 query | 2016-08-10 18:11:39.252000+0000
`

**Comment by ifesdjeen** [comment]
@tehlers320 could you please tell me, whats the cardinality of `collectd_metrics.cyanite-cassandra` keyspace? 

Just a count with this as a partition key would do. I guess that partition sizes are still much too large. I have one more possible optimisation for direct queries though, if my guess about cardinalities is true, I can try it.

**Comment by tehlers320** [comment]
```
SELECT count(*) from metric.segment where segment LIKE 'collectd_metrics.cyanite-cassandra%' AND pos = 5;

 count
-------
    55

(1 rows)
cqlsh> SELECT count(*) from metric.segment where segment LIKE 'collectd_metrics.cyanite-cassandra%' ;

 count
-------
    97

(1 rows)

Warnings :
Aggregation query used without partition key

```

This is **not** querying collectd_metrics.cyanite-cassandra

I cleared my system_trace.sessions table and put a curl in a while loop for:

`while true; do time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-2-92-19.aggregation-cpu-average.percent-user && sleep 30;done
`
```
cqlsh 10.2.92.37 -e 'select * from system_traces.sessions where duration > 10 allow filtering' |grep collectd| cut -d \| -f6 |sort |uniq -c
    150   {'consistency_level': 'LOCAL_ONE', 'page_size': '5000', 'query': 'SELECT * from segment where segment LIKE ''collectd_metrics%'' AND pos = 5', 'serial_consistency_level': 'SERIAL'} 

```

Now clearing the entire sessions table i re-run this test with 

`while true; do time curl localhost:8080/paths?query=collectd_metrics.cyanite-cassandra.ip-10-2-*.aggregation-cpu-average.percent-user && sleep 30;done`

```
cqlsh 10.2.92.37 -e 'select * from system_traces.sessions where duration > 1 allow filtering' |grep collectd| cut -d \| -f6 |sort |uniq -c

      1  {'consistency_level': 'LOCAL_ONE', 'page_size': '5000', 'query': 'SELECT * from segment where segment LIKE ''collectd_metrics.cyanite-cassandra.ip-10-2-%'' AND pos = 5', 'serial_consistency_level': 'SERIAL'} 

```

I think this is a bug.

**Comment by ifesdjeen** [comment]
This bug was fixed by now, thank you for reporting!

**Comment by pyr** [comment]
Thanks @ifesdjeen !

**Comment by ifesdjeen** [comment]
<3 @pyr

**Comment by ifesdjeen** [comment]
I'm sorry looks like I had 4 unpushed commits. I rebased and merged them all to Master.

Thank you again!

**Pull request merged**
