### PR TITLE
include path in NaN line exceptions

### PR DESCRIPTION
**Pull request by jshook**
Just a simple change to make it easier to see NaN paths.

### CODE REVIEW

**Comment by pyr** [comment]
hi @jshook. This is a good idea, can you also add the path to the ex-info map please?

**Comment by jshook** [comment]
@pyr
It is done.

**Comment by pyr** [comment]
Thanks @jshook

**Comment by dalassi** [comment]
Hi, I see similar error when sending CollectD stats to Cyanite. This CollectD instance works fine sending its stats to a Graphite instance. But when I send the same stats to Cyanice, I get the following exceptions:
clojure.lang.ExceptionInfo: invalid carbon line: NaN metric for path:collectddops-dev01collectd.protocols-Tcp.protocol_counter-CurrEstab
        at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.input.carbon$parse_line.invokeStatic(carbon.clj:22) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.input.carbon$parse_line.invoke(carbon.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.input.carbon$pipeline$fn__11703.invoke(carbon.clj:40) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.input.carbon.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) ~[cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [cyanite-0.5.1-standalone.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite-0.5.1-standalone.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

I see NULL id and point in the Metric table in Cassandra. When I use the fake tool ( in the perf directory of source code), I get the same thing.

Am I missing something or the version currently in master is broken?

Thanks!
Derar

**Pull request merged**
