### PR TITLE
Updated core

### LINKED ISSUE #1: allow choosing resolution by path regexp
The configuration should allow specifying alternate rollup strategies based on path regexes

### LINKED ISSUE #48: pickle receiver support?
I am currently running a carbon-relay -> carbon-aggregator -> carbon-cache setup and since carbon-cache performs poor I am looking into alternative backends.

To be able to use cyanite as a carbon-cache replacement it needs to accept metrics in as python pickles since this is how carbon-aggregator forwards metrics to carbon-cache.

I have found your interesting blog-post [1] about the python pickle format but I wasn't able to find out if it is already possible, and if so how, to configure cyanite to accept carbon's pickle output.

It would be great if you could give me a hint. I'm happy to contribute documentation updates as a pull request if you could point out here how to achieve this.

[1] http://spootnik.org/entries/2014/04/05_diving-into-the-python-pickle-format.html

### PR DESCRIPTION
**Pull request by pyr**
Updated Core: Design and Concepts
===========================

Status
---------

- [X] fixes #1
- [X] fixes #48
- [x] normalize series when multiple resolutions are returned
- [x] bring back ES support

Internal Architecture
--------------------------

Cyanite's internal architecture is that of the typical
stream processing project, it connect inputs to outputs
while doing normalization and mangling.

The internal architecture can be represented with this
simple diagram:

architecture

As is described on the diagram the workflow is:

- Each input produces new normalized payloads (*metrics*),
  and enqueues them.
- The engine core pops items off the queue and processes them
- When applicable items are handed off to a *store* and *index*.
  components respectively responsible for persisting time-series
  and indexing metric names.
- An API component which is able to interact with the engine
  and other components to query and present data.

Input Components
------------------------

Input components are arbitrary means of inputting metrics.
Out of the box there are three available types of input
components:

- `carbon`: a TCP listener for the text protocol known as *Carbon*,
  which is part of the *Graphite* tool-suite.
- `pickle`: a pickle serialized version of the above protocol, as
  produced by the other daemons in the *Graphite* tool-suite.
- `fake`: a fake input which produces a new value every 500
  milisecond for test purposes.

Input components are responsible for producing metrics in a normalized
way:

```json
  {
    "path":   "web01.cpu",
    "metric": 40.0,
    "time":   1437572671
  }
```

Once a metric has been normalized, it is handed over to the engine
component through its ``accept!`` function:

```clojure
    (accept! engine {:path "web01.cpu" :metric 40.0 :time 1437572671})
```

Engine Component
----------------

The engine component is responsible for popping metrics off of its
input queue, aggregating data over a time-window and producing write
operations on the index and store components when necessary.

To do this it holds on available points for a while and flushing them
out when necessary.

>   The fact that Cyanite holds on to metrics in memory makes it a
>  stateful server. As such if you wish to use Cyanite in a redundant
>   fashion, you will need to account for it.

#### Aggregation Mechanism

The aggregation mechanism for metrics relies on a fast in-memory
hash-table. Each metric is kept on a bucket corresponding to the
metric path and its resolution. When a time-window has passed for a metric
sums, means, minimas and maximas are computed and emitted as a /snapshot/.

Cyanite supports several resolutions based on a first-match set of rules
as provided in the configuration file. Rules are a list of patterns
to match a metric name on corresponding to a list of resolutions
(in the form `<precision>:<period>`).

Snapshots are then handed over to the store and index components.
The process can be represented visually like this:

architecture

>   Cyanite accounts for drift by comparing its wall clock to the values provided in metrics.
>   Once a resolution's time-slot passes over including when accounting for drift, values are
>   flushed and a snapshot is created. This means that out-of-order values may be supplied but
>   not once a time-slot has already been flushed.

Store component
---------------

The store component is called for each snapshot created by the engine component.
The only working component stores data to Apache Cassandra

#### Storage Schema

The following schema is used to store data::

    CREATE KEYSPACE metric
           WITH replication = {'class': 'SimpleStrategy',
                               'replication_factor': '1'}
           AND durable_writes = true;

    USE metric;

    CREATE TYPE metric_point (
      max double,
      mean double,
      min double,
      sum double
    );

    CREATE TYPE metric_id (
      path text,
      resolution text
    );

    CREATE TABLE metric.metric (
      id frozen<metric_id>,
      time bigint,
      point frozen<metric_point>,
      PRIMARY KEY (id, time)
    ) WITH COMPACT STORAGE
      AND CLUSTERING ORDER BY (time ASC)
      AND compaction = {'min_threshold': '4',
                       'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy',
                       'max_threshold': '32'}
      AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
      AND dclocal_read_repair_chance = 0.1
      AND default_time_to_live = 0
      AND gc_grace_seconds = 864000
      AND max_index_interval = 2048
      AND memtable_flush_period_in_ms = 0
      AND min_index_interval = 128
      AND read_repair_chance = 0.0
      AND speculative_retry = '99.0PERCENTILE';
  
This schema leverages Cassandra's `Compact Storage` option to ensure a minimal overhead.
Please be sure to choose the optimal compaction strategy for your use case. If available
the `DateTieredCompactionStrategy` is likely your best bet.

Index Component
---------------

The index component is responsible for building an index of path names and providing
a way of querying them back. There are two implementations of this component available:

- `memory` stores an in-memory inverted index.
- `elasticsearch` stores path-names in elasticsearch.

>   The `memory` index is a poor choice for redundant setups since it will only know of
>   metrics passing through it. Additionally, it is only valid to use it when metric name
>   cardinality is limited and metrics are recurrent since it will lose all its index upon
>   restarts.

API Component
-------------

The API component is responsible for exposing an HTTP service to service queries.
The API component exposes the following HTTP routes:

- `/ping`: report online status
- `/metrics`: query metrics.  Takes `from`, `to` (optional), and any number of  `path` arguments.
- `/paths`: query paths.  Takes a `query` argument.

Any other request will yield a 404 response.

### CODE REVIEW

**Comment by stdweird** [comment]
@pyr i'm interested in trying cyanite with pickle receive support. is the the PR to try for that? (i'll can try to resolve the merge issues, i'll report back with any issues i encounter)

**Comment by pyr** [comment]
Hi, Indeed that's where the work on pickle is going on.
I intend to get back to it in May, sorry about the delay.

**Comment by pyr** [comment]
To anyone following along, we're now back in a working state for metrics which will be compatible with previous cyanite installations. Please pay attention to the updated schema. There are no migration tools yet, these will be provided separately.

**Comment by jippi** [comment]
looks super nice!

**Comment by jeffpierce** [comment]
@pyr Looks good, especially after watching 9 Cassandra nodes undergo a 1TB compaction simultaneously and hoping the cluster didn't fall over before it completed!

**Comment by SEJeff** [comment]
Any chance this will eventually add more inputs?

A few I can think of that might be nice:
* Kafka 
* protobuf / captain proto

**Comment by pyr** [comment]
@SEJeff I intend to add more inputs indeed. Protobuf will most likely make it in the core in the form of a riemann input. As far as kafka is concerned, I intend to provide it as a plugin which will be able to:

- process metrics as emitted by collectd, syslog-ng and other common emitters of kafka metrics
- ship-off metrics to kafka (for name indexing purposes for instance)

I also intend to promote kafka as the recommended option when scaling cyanite installations.

**Comment by chjohnst** [comment]
Going to check this out tonight, when do you think migration scripts will
be available to go from the old schema to the new?

**Comment by pyr** [comment]
@chjohnst Hi! I intend to provide two ways to migrate:

- A compatibility mode with the old schema
- A migration tool from the old to the new schema

**Comment by chjohnst** [comment]
Fantastic might be worth discussing the implementation of that setup.

**Comment by pyr** [comment]
I've brought back ES indexing support here as well. Here is how this will play out:

- Documents will be indexed by the Murmur3 hash of a path to avoid reindexing
- Documents will contain a `length` and `path` field
- Documents are inserted with a TTL corresponding to their resolution
- `path` will be stored, `length` will not. Neither will be analyzed
- Leave queries will enforce length to be the number of segments
- All queries will perform an additional wildcard match on the given path query

At startup, a query will be performed on the appropriate type to tentatively insert a valid ES mapping for the type.
ElasticSearch indexing will also greatly benefit from the snapshotting mechanism that this PR implements since a path will only be indexed once per resolution window.

There will be further improvements to make here:

-  Indexing should only happen once for a metric, not for each (metric,resolution) tuple as it is the case right now

**Comment by pyr** [comment]
Alright, flipping the switch. Next up:

- doc polish
- inline doc
- a real test-suite

Once this is done, I'll go ahead and shoot a release. Don't hesitate to chip in here with any feedback you may have.

**Comment by tjamesturner** [comment]
i could be wrong, but it looks like this new architecture pre-aggregates longer retention periods in-memory.  won't this cause problems for clustered environments where datapoints for the same long-retention bucket could go to different cyanite servers?

**Comment by pyr** [comment]
@tjamesturner yes, as mentioned in #106 and in the docs, you'll have to do client-side hashing

**Pull request merged**
