### PR TITLE
Make communication with Cassandra more reliable

### LINKED ISSUE #76: Fails when a cassandra node goes down
Cyanite fails when a cassandra nodes goes down even if redundancy/consistency are still satisfied.

Configuration:

Cyanite is connected to a local cassandra instance (A) which is connected with two other cassandra nodes (B, C).

cyanite.yaml
```
carbon:
  host: "127.0.0.1"
  port: 2004
  rollups:
    - "1m:30d"
    - "5m:90d"
http:
  host: "127.0.0.1"
  port: 8000
logging:
  level: warn 
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
store:
  cluster: 'localhost'
  keyspace: 'metric'
  chan_size: 10000 
  batch_size: 1000
index:
  use: "io.cyanite.es_path/es-rest"
  index: "cyanite_paths"
  url: "http://localhost:9200"
```

Cassandra:
```
CREATE KEYSPACE metric WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3};
```

Note: replication factor 2 makes no difference.

Steps to reproduce:

1. All cassandra nodes up (check with nodetool)
2. Start cyanite
3. Take down either node B oder node C

Cyanite fails with:

```
async-dispatch-29 - io.cyanite.store - Cassandra error
clojure.lang.ExceptionInfo: Query execution failed {:values nil, :query #<BatchStatement com.datastax.driver.core.BatchStatement@48b34d74>, :type :qbits.alia/execute, :exception #<NoHostAvailableException com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)>}
	at clojure.core$ex_info.invoke(core.clj:4554)
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:167)
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:169)
	at qbits.alia$execute_chan$reify__6658.onFailure(alia.clj:300)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This failure persistents even when all node are available again.

Strange behaviour:

When cyanite is started while node B or node C are already down no errors appear. It's possible to take node B or C up and down with no side effects on cyanite then.

I tried  passing ":consistency: any" to all alias/execute(-chan) calls but this did no help.

### PR DESCRIPTION
**Pull request by MichaelHierweck**
Both update of alia and datastax cassandra driver and applying a fixed reconnection period improve the behavior when a cassandra node in a cluster goes down and/or comes up again.

This fixes #76.

### CODE REVIEW

**Comment by ogg1e** [comment]
I like the reconnection fix. That should be merged.

**Comment by chjohnst** [comment]
Will this be merged?

**Comment by pyr** [comment]
Hi Chris,

I've just picked up the slack on cyanite and will be looking at merging this quite soon. Sorry again for the delay.

Cheers,
  -pyr

**Comment by chjohnst** [comment]
Cool no problem, I have a pretty big cyanite deployment right now (24
Cassandra nodes and 10 cyanite instances).  Would be good to share some of
my experiences with it and where some improvements could be made if you
have time.

**Comment by pyr** [comment]
I'm taking this in as part of #80. My goal is to end up with something that allows a more flexible cassandra configuration, by providing an easy way to defer to alia's configuration.

**Pull request closed without merging**
