### PR TITLE
engine: switch to constant-space operations

### PR DESCRIPTION
**Pull request by pyr**
This is work in progress, no snapshoting is done which means
memory will grow unbounded and no writes will occur, follow-up
commits will rework tests and bring back snapshotting.

This draws ideas from the discussion in #183.

The basic idea is that the engine now hold a global non-blocking hash-map associating metric paths with a list of resolutions.

Each resolution holds a list of *Monoids* which hold the current accumulator values. The monoids implement IDeref to snapshot state.

- [X] implement snapshotting
- [X] switch snapshotting to a recurring process
- [X] always use the clock as acomponent
- [ ] prune internal state of empty timeslots to allow GC for disappearing metrics
- [X] implement a simple threadpool for recurring processes
- [ ] keep track of a timestamp floor, accounting for drift, allowing to discard measures that come in too late and would

### CODE REVIEW

**Comment by ifesdjeen** [comment]
Looks really good!

**Comment by pyr** [comment]
Thanks, I'll try to have snapshoting done tonight so I can work on docs & tests for the code.
Between this and your disruptor code we should start to be in good shape for most workloads.

**Comment by ifesdjeen** [comment]
Great! Looking forward to see the rest, too.

Meanwhile, I've covered the `run-test!` with tests. Most likely I'll leave the "dirty" version for now to avoid merges and will clean the test / system creation after the both PRs. Also, I've done some changes in `ast` and covered them with tests too. Need to shuffle out a couple of rough edges and i'm good to go too.

**Comment by pyr** [comment]
:+1:

**Comment by ifesdjeen** [comment]
Question: if, due to the latencies or for whatever reason it happens that snapshot is incomplete after the timeout, should we still flush the snapshot? Or should we normalize by metric ticks somehow?

**Comment by pyr** [comment]
What do you mean by an incomplete snapshot?

**Comment by ifesdjeen** [comment]
For example, the metric that belonged to the particular 5-second interval, came with 100 milliseconds delay for whatever reasons. It will be simply taken to the next 5 seconds, or?

**Comment by pyr** [comment]
Nope, the way it works is:

- A metric comes in, we look at its `:time` tag and for a resolution chain, we figure out which timeslot it falls into and record that.
- We account for drift by comparing the `:time` tags to our clock's notion of tag, the drift component holds on to that difference.
- At regular interval we snapshot and flush for writes timeslots which fall **strictly** below `(- (epoch!) drift)

The one thing we don't do just yet is keeping a high watermark of the recorded time we already flushed at to discard incoming measures coming in after that. What will happen for those is that they will update the drift but still be discarded for the first time (otherwise we would recreate a snapshot and overwrite it in cassandra).

Does that make sense?

**Comment by ifesdjeen** [comment]
> The one thing we don't do just yet is keeping a high watermark of the recorded time we already flushed at to discard incoming measures coming in after that. 

Great, that was along the lines of what I had in mind. I think I got the rest mostly correctly. Perfect.

**Comment by pyr** [comment]
For the inner-range stuff, you are not supposed to mix resolutions when returning data, so I'm not sure what we could infer with `(resolution rules from to)` which we cannot with `(resolution rules from)`, can you expand on what you think becomes possible?

**Comment by pyr** [comment]
(btw i added the high-watermark comment in the todo-list in the PR description)

**Comment by ifesdjeen** [comment]
I was mostly wondering, if you do the query for just a single metric (for example `a.b.c`) and you query from `now-6h` until `now-3h`. Current logic would calculate resolution for `now-6h` until `now`. 

This might make it more difficult for test purposes too, where putting the particular timestamp would involve rounding and relative calculations, and using absolute timestamps for ranges just allows passing them to the function.

**Comment by pyr** [comment]
I understand. My take on it is that this merges two things:

- 1. The best possible resolution for a time-range
- 2. The subset of data that you are interested in

For 1., only from is relevant and this code is used at both insert-time and query time, so I would keep it as-is.
For 2. we need both and it indeed seems that there is nothing which discards more recent data in the current code, which will need to happen (but is a concern best address in your other PR).

**Comment by ifesdjeen** [comment]
Ok, cool. Then I'll stick to the plan and rebase whenever that one is merged.

**Comment by pyr** [comment]
I hopefully shouldn't keep you waiting too long

**Comment by ifesdjeen** [comment]
Heh, no problem, I'm not in a rush at all. There are enough of things to look at / take care of.

**Comment by pyr** [comment]
@ifesdjeen I'll make the remaining open points new issues and merge this for now, since it will allow you to get moving with your PR.

**Comment by ifesdjeen** [comment]
W0000t! Great job, thanks for megring!

**Pull request merged**
