### PR TITLE
Bring in Graphite query parser and Cassandra metric index

### PR DESCRIPTION
**Pull request by pyr**
Improve performance and Graphite compatibility.

- [X] Refactor search interface
- [X] Cassandra search implementation
- [X] Graphite query parser
- [X] Load test procedure

Refactor search interface
-------------------------

The search functionality now puts a lot less responsibility in
the hands of implementers. Three functions are now expected from
implementations:

```clojure
(defprotocol MetricIndex
  (push-segment! [this pos segment path length])
  (by-pos        [this pos])
  (by-segment    [this pos segment]))
```

Based on these primitives, cyanite now builds a simple inverted
index of the following structure, given the input paths:
`collectd.web01.cpu` and `collectd.web02.cpu`:

```javascript
{
  "segments": {
    0: [ "collectd" ],
    1: [ "web01", "web02" ],
    2: [ "cpu" ]
  },
  "paths": {
    [0, "collectd"]: [["collectd.web01.cpu", 3], ["collectd.web02.cpu", 3]],
    [1, "web01"]:    [["collectd.web01.cpu", 3]],
    [1, "web02"]:    [["collectd.web02.cpu", 3]],
    [2, "cpu"]:      [["collectd.web01.cpu", 3], ["collectd.web02.cpu", 3]]
  }
}
```

Given this structure, cyanite will now split paths into segments, and perform
globbing queries on segments.

- `push-segment!`: Register a new path.
- `by-pos`: Yield all segments at a given position
- `by-segment`: Yield paths for a position and segment tuple

The globbing implementation is somewhat naive and leaves room for improvement,
implementations should aim to sort segments. Subsequent commits will bypass
`by-pos` whenever possible and perform prefix lookups up to the first wildcard
to further reduce lookup times.

Two implementations of this protocol are provided:

- `AgentIndex` stores segments and paths in memory, updates go through an agent.
- `CassandraIndex` provides Cassandra-backed storage for paths and segments.

The ElasticSearch-backed index is now gone, but a compatible implementation will
be provided as a subsequent improvement.

Graphite Query Parser
---------------------

A tokenizer for the Graphite syntax has been living in the tree for a while.
A subset of the syntax is now handled, and may be translated to an AST.

A `run-query!` function is also provided which will walk tokens to
extract paths, query paths, handling globs and will then be reduced
to the result of the operation if successful.

The following operations are already implemented:

- `sumSeries`
- `divideSeries`
- `scale`
- `absolute`

Globbing is handled by https://github.com/pyr/globber and adheres to
globbing rules as available in common shells.

Load testing procedure
----------------------

Cyanite now integrates https://github.com/feangulo/graphite-stresser for
development, the baseline against which it is tested is a workload
of 200000 metrics per second, flushed at at 5 second interval with
a maximum heap-size of 512m.

Remaining work
--------------

These changes fix & improve the following on-going issues:

- #119
- The path indexing part of #121.
- Most of the work needed for #136.

### CODE REVIEW

**Comment by vincentbernat** [comment]
:dancers:

**Comment by altvnk** [comment]
Cyanite cannot start with:
```
index:
  type: memory
```
and it's ok i suppose, commented this block and it can start.
So question is how to enable cassandra index? in memory index is still default one?

**Comment by pyr** [comment]
Hi @altvnk,

The name of the index type is now `agent`. You can also now use `cassandra` as an alternative index type. I will update the documentation shortly.

**Comment by altvnk** [comment]
Thank, now it's clear.

PS: After writing this comment i realised to search sources for `:type` and found all references. Sorry for noise here...

**Comment by altvnk** [comment]
For some reason `type: cassandra` crashes cyanite. Here is exception:
```
WARN [2015-10-18 00:36:50,982] main - io.cyanite uncaught exception
clojure.lang.ExceptionInfo: Error in component :index in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/start
	at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$try_action.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system$fn__317.invoke(component.cljc:139) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6536) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system.doInvoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.main(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
	at qbits.alia.cluster_options$fn__9222.invokeStatic(cluster_options.clj:35) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia.cluster_options$fn__9222.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:238) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia.cluster_options$set_cluster_options_BANG_$fn__9365.invoke(cluster_options.clj:285) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6734.invokeStatic(protocols.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6734.invoke(protocols.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6676$G__6671__6689.invoke(protocols.clj:13) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6537) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia.cluster_options$set_cluster_options_BANG_.invokeStatic(cluster_options.clj:284) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia.cluster_options$set_cluster_options_BANG_.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia$cluster.invokeStatic(alia.clj:184) ~[cyanite-0.5.1-standalone.jar:na]
	at qbits.alia$cluster.invoke(alia.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index.cassandra$session_BANG_.invokeStatic(cassandra.clj:47) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index.cassandra$session_BANG_.invoke(cassandra.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index.cassandra.CassandraIndex.start(cassandra.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$fn__266$G__260__268.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$fn__266$G__259__271.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:647) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$apply.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117) ~[cyanite-0.5.1-standalone.jar:na]
	... 16 common frames omitted
```

**Comment by pyr** [comment]
what options are you using?

```yaml
index:
  type: cassandra
  options:
    cluster: localhost
```

**Comment by altvnk** [comment]
Hmm... Nope, just `type: cassandra`, i thinked that it uses same cluster connection as for metrics storage. I will check it with options.

**Comment by altvnk** [comment]
Cool, now it woks. But loading metrics in grafana is so slow. Maybe i'm experiencing some problems with cassandra, not sure. How it worked for you?
Btw, rendering endpoint returns empty dataset, grafana reports `No datapoints`. This happening with index `agent` and `cassandra` as well. Request from log:
```
DEBUG [2015-10-18 01:18:39,040] nioEventLoopGroup-3-1 - io.cyanite.query running query:  "STRESS.host.ip-0.com.graphite.stresser.a.count"
DEBUG [2015-10-18 01:19:09,574] nioEventLoopGroup-3-1 - io.cyanite.api got request:  {:uri "/render", :get-params {}, :body-params {:target "STRESS.host.ip-0.com.graphite.stresser.a.count", :from "-6h", :until "now", :format "json", :maxDataPoints "1440"}, :params {:target "STRESS.host.ip-0.com.graphite.stresser.a.count", :from "-6h", :until "now", :format "json", :maxDataPoints "1440"}, :request-method :post, :version "HTTP/1.1", :headers {:referer "http://192.168.99.100:3000/dashboard/new", :user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36", :host "192.168.0.109:8080", :content-length "103", :accept-encoding "gzip, deflate", :content-type "application/x-www-form-urlencoded", :origin "http://192.168.99.100:3000", :accept-language "ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4,uk;q=0.2", :x-forwarded-for "192.168.99.1", :x-xsrf-token "1br8hzADcBGPQizIr2BbWyvQM/651wAxEacLyCZkvXw=", :accept "application/json, text/plain, */*"}, :body "target=STRESS.host.ip-0.com.graphite.stresser.a.count&from=-6h&until=now&format=json&maxDataPoints=1440"}
```
Also it pops exception when finds underscore in metric, i.e.:
```
DEBUG [2015-10-18 01:28:05,232] nioEventLoopGroup-3-1 - io.cyanite.query running query:  "STRESS.host.ip-0.com.graphite.stresser.a.m15_rate"
ERROR [2015-10-18 01:28:05,330] nioEventLoopGroup-3-1 - io.cyanite.api could not process request
clojure.lang.ExceptionInfo: unsupported function in cyanite
	at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query.ast$fn__11028.invokeStatic(ast.clj:138) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query.ast$fn__11028.invoke(ast.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query.ast$run_query_BANG_.invokeStatic(ast.clj:143) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query.ast$run_query_BANG_.invoke(ast.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query$run_query_BANG_.invokeStatic(query.clj:46) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.query$run_query_BANG_.invoke(query.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$fn__11399.invokeStatic(api.clj:125) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$fn__11399.invoke(api.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$process.invokeStatic(api.clj:89) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$process.invoke(api.clj) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$make_handler$fn__11415.invoke(api.clj:152) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http$request_handler$fn__11136.invoke(http.clj:109) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http$netty_handler$fn__11144.invoke(http.clj:122) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite-0.5.1-standalone.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```
If needed i'll create separate issues for this cases. Let me know if it's needed.

**Comment by pyr** [comment]
@altvnk The underscore in metric issue is now fixed. There will be a lot of tests to add to the DSL parser, since it's quite new and I don't think I understood all corner cases in the original graphite syntax.

**Comment by pyr** [comment]
@altvnk what setup are you using for fetching metrics in grafana? through graphite-api?

**Comment by altvnk** [comment]
I've tried to use grafana with cyanite directly.

**Comment by pyr** [comment]
This is still heavily WIP. I expect it to be much better by next week (I cannot devote too much time to cyanite this week). There are still some things which do not work and for which the parser will need to be updated. But it's now coming really close to being ready.

**Comment by hryamzik** [comment]
Did you test this version with graphite-api? ```http://127.0.0.1:8001/metrics/find?query=*``` returns me the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/app.py", line 135, in metrics_find
    key=lambda node: node.name
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/storage.py", line 22, in find
    for node in finder.find_nodes(query):
  File "/usr/local/lib/python2.7/dist-packages/cyanite.py", line 121, in find_nodes
    paths = truncate_nodes(query.pattern, paths)
  File "/usr/local/lib/python2.7/dist-packages/cyanite.py", line 41, in truncate_nodes
    qpath = '.'.join(path.split('.')[:count])
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by chjohnst** [comment]
Which version of graphite-api are you on?

**Comment by hryamzik** [comment]
@chjohnst
```
graphite-api==1.1
cyanite==0.4.6
```

**Comment by hryamzik** [comment]
In fact I've added some log output:

```python
    for path in paths:
        # Get the first 'count' parts of the path name.
        logger.error('path: %s' % path)
        qpath = '.'.join(path.split('.')[:count])
```

And here's how it look like:

```
2015-10-20 19:13:47,964 ERROR path: {u'leaf': 0, u'text': u'stats', u'path': u'stats', u'expandable': 1, u'allowChilren': 1, u'id': u'stats'}
```

And here's the queue to cyanite:

```
# curl -s http://172.28.128.3:8080/paths?query=*
[{"path":"stats","text":"stats","id":"stats","allowChilren":1,"expandable":1,"leaf":0},{"path":"stats_counts","text":"stats_counts","id":"stats_counts","allowChilren":1,"expandable":1,"leaf":0},{"path":"statsd","text":"statsd","id":"statsd","allowChilren":1,"expandable":1,"leaf":0}]
```

**Comment by chjohnst** [comment]
Can you try graphite-api 1.1 + this patch?  This looks similar to watch I
saw in recent tests against graphite-api + cyanite.

https://github.com/brutasse/graphite-api/commit/90ba6d304917a533f682e46f5b369fc52a6dc62f

**Comment by brutasse** [comment]
@hryamzik you have a patched version of graphite-cyanite. `truncate_nodes` doesn't exist in the upstream repo. Please uninstall it and reinstall it again, this should fix your issue.

**Comment by hryamzik** [comment]
@chjohnst wow, my bad, in works in test now! And after I've created new tables in an old installation it started as well, thanks!

**Pull request merged**
