### PR TITLE
Improvement/add index integration tests

### PR DESCRIPTION
**Pull request by ifesdjeen**
I'm trying to investigate some issues reported by users, and it turned out to be simpler to reproduce with tests. I thought it might be useful for other people who're developing / working with code, so I added "integration" test framework that includes cassandra (via ccm) for testing purposes.

It's out of the box, and (should) work seamlessly for anyone having python and pip installed.

### CODE REVIEW

**Comment by ifesdjeen** [comment]
I've added a bit more "helpers" in order to help the new possible contributors. I've brought in `grafana` and `stress`, also cassandra setup.

`Contributing.md` is updated accordingly.

**Comment by ifesdjeen** [comment]
I've added a couple of critical fixes that should solve #156, it would be just great if we could get them merged :)

**Comment by pyr** [comment]
Thanks @ifesdjeen !

**Comment by ifesdjeen** [comment]
THANKS!!!

**Pull request merged**
