### PR TITLE
Add instrumentation to queues

### PR DESCRIPTION
**Pull request by ifesdjeen**
I think I'll work on the `derivative` next, so that we could take a full advantage of those.

### CODE REVIEW

**Comment by pyr** [comment]
hey, this is awesome. i think i might highjack this PR to wire-in https://spootnik.org/pyr/reporter, so we set-up and teardown the metrics registries from the component system, would you mind?

If so i'll wait until you finish adding the metrics you're interested in and then i'll switch counter/gauges/... creation to use the reporter semantics.

**Comment by ifesdjeen** [comment]
sounds good. 
I don't have metrics in mind at the moment, I'm trying to make `derivative` work :) so go ahead

**Comment by pyr** [comment]
I'll get on it.

**Comment by pyr** [comment]
Ideally we will later add an internal metric-reporter so which calls `accept!` on the engine.

**Comment by ifesdjeen** [comment]
LGTM

**Comment by ifesdjeen** [comment]
Should we merge that?

**Comment by pyr** [comment]
guess so!

**Pull request merged**
